# Generated by Django 3.0.8 on 2020-07-31 07:47

from django.db import migrations

from .util import fill_id_primary_key


def fill_user_ids(apps, schema_editor):
    """
    Fill user with surrogate primary key 'id'
    """
    Users = apps.get_model("chat_posts", "Users")
    fill_id_primary_key(Users)


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0002_add_dummy_id"),
    ]

    operations = [migrations.RunPython(fill_user_ids)]
