# Generated by Django 3.0.8 on 2020-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0003_fill_id"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("ALTER TABLE Users DROP PRIMARY KEY;")],
            reverse_sql=[("ALTER TABLE Users ADD PRIMARY KEY (name);")],
            state_operations=[
                migrations.AlterField(
                    model_name="users",
                    name="name",
                    field=models.CharField(max_length=30, unique=True),
                )
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
