# Generated by Django 3.0.8 on 2020-08-06 06:30

from django.db import migrations

def add_old_posts(apps, schema_editor):
    
    LegacyPosts = apps.get_model('chat_posts', 'LegacyPosts')
    Posts = apps.get_model('chat_posts', 'Posts')

    Posts.objects.bulk_create(
        LegacyPosts.objects.all(), batch_size=10000
    )



class Migration(migrations.Migration):

    dependencies = [
        ('chat_posts', '0005_auto_increment'),
    ]

    operations = [
        migrations.RunPython(add_old_posts)
    ]

