# Generated by Django 3.0.8 on 2020-08-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_posts', '0006_add_old_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='ChatUsers',
        ),
        migrations.AlterModelOptions(
            name='LegacyPosts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='allowedin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='censors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chatcontrols',
            options={},
        ),
        migrations.AlterModelOptions(
            name='currentposts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailyposts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emoticons',
            options={},
        ),
        migrations.AlterModelOptions(
            name='handleof',
            options={},
        ),
        migrations.AlterModelOptions(
            name='handles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oldssuposts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomadmins',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skins',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trumppost',
            options={},
        ),
        migrations.AlterModelTable(
            name='chatusers',
            table=None,
        ),
    ]
