# Generated by Django 3.0.8 on 2020-08-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0007_manage_tables"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Censors",
        ),
        migrations.DeleteModel(
            name="LegacyPosts",
        ),
        migrations.DeleteModel(
            name="ChatControls",
        ),
        migrations.DeleteModel(
            name="CurrentPosts",
        ),
        migrations.DeleteModel(
            name="DailyPosts",
        ),
        migrations.DeleteModel(
            name="OldSSUPosts",
        ),
        migrations.DeleteModel(
            name="Profiles",
        ),
        migrations.DeleteModel(
            name="Skins",
        ),
        migrations.DeleteModel(
            name="TrumpPost",
        ),
    ]
