# Generated by Django 3.0.8 on 2020-08-06 07:28

from django.db import migrations, models

from .util import fill_id_primary_key


def fill_user_ids(apps, schema_editor):
    """
    Fill user with surrogate primary key 'id'
    """
    Rooms = apps.get_model("chat_posts", "Rooms")
    fill_id_primary_key(Rooms)


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0008_drop_unused_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="Rooms",
            name="id",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(fill_user_ids),
        migrations.RunSQL(
            sql=[("ALTER TABLE Rooms DROP PRIMARY KEY;")],
            reverse_sql=[("ALTER TABLE Rooms ADD PRIMARY KEY (name);")],
            state_operations=[
                migrations.AlterField(
                    model_name="Rooms",
                    name="name",
                    field=models.CharField(max_length=30, unique=True),
                )
            ],
        ),
    ]
