# Generated by Django 3.0.8 on 2020-08-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_posts', '0011_add_int_to_handles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handles',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='handles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='handles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
