# Generated by Django 3.0.8 on 2020-08-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_posts', '0012_create_handle_pk'),
    ]

    operations = [

        migrations.RunSQL(
            sql=[('ALTER TABLE Posts DROP PRIMARY KEY;')],
            reverse_sql=[('ALTER TABLE Posts ADD PRIMARY KEY (tstamp, handlename, roomname, usertopm);')],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='posts',
                    unique_together=set(),
                ),
                migrations.AlterField(
                    model_name='posts',
                    name='tstamp',
                    field=models.DateTimeField(db_column='tStamp'),
                ),
            ]
        ),
        migrations.RunSQL(
            sql=[('ALTER TABLE Posts ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;')],
            reverse_sql=[
                ('ALTER TABLE Posts DROP PRIMARY KEY;'),
                ('ALTER TABLE Posts DROP COLUMN id;'),
            ],
            state_operations=[
                migrations.AddField(
                model_name='Posts',
                name='id',
                field=models.IntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name='posts',
                    name='id',
                    field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                )
            ]
        )
    ]
