# Generated by Django 3.0.8 on 2020-08-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0013_add_int_to_posts"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="emoticons",
            table=None,
        ),
        migrations.AlterModelTable(
            name="handles",
            table=None,
        ),
        migrations.AlterModelTable(
            name="posts",
            table=None,
        ),
        migrations.AlterModelTable(
            name="roomadmins",
            table=None,
        ),
        migrations.AlterModelTable(
            name="rooms",
            table=None,
        ),
    ]
