# Generated by Django 3.0.8 on 2020-08-26 07:07

from django.db import migrations


def add_chat_posts(apps, schema_editor):

    Rooms = apps.get_model('chat_posts', 'Rooms')

    Rooms.objects.get_or_create(name='Old SSU')


class Migration(migrations.Migration):

    dependencies = [
        ('chat_posts', '0015_posts_room'),
    ]

    operations = [
        migrations.RunPython(add_chat_posts),
        migrations.RunSQL(
            "UPDATE chat_posts_posts "
            "JOIN chat_posts_rooms "
            "ON chat_posts_posts.roomName = chat_posts_rooms.name "
            "SET chat_posts_posts.room_id = chat_posts_rooms.id;"
        )
    ]
