# Generated by Django 3.0.8 on 2020-09-17 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0016_add_room_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="handle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat_posts.Handles",
            ),
        ),
    ]
