# Generated by Django 3.0.8 on 2020-09-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0019_add_user_fk_to_handle"),
    ]

    operations = [
        migrations.RunSQL(
            [
                (
                    "UPDATE chat_posts_handles "
                    "JOIN HandleOf "
                    "ON chat_posts_handles.name = HandleOf.handleName "
                    "JOIN chat_posts_chatusers "
                    "ON HandleOf.userName = chat_posts_chatusers.name "
                    "SET chat_posts_handles.chat_user_id = chat_posts_chatusers.id;"
                )
            ]
        )
    ]
