# Generated by Django 3.0.8 on 2020-09-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0020_add_user_data_to_handle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allowedin",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="handleof",
            options={"managed": True},
        ),
    ]
