# Generated by Django 3.0.8 on 2020-09-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0021_make_tables_managed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllowedIn",
        ),
        migrations.DeleteModel(
            name="HandleOf",
        ),
        migrations.DeleteModel(
            name="RoomAdmins",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="avatarlimit",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="chatcontrol",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="chatlimit",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="emoticons",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="frameborder",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="framestyle",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="javascript",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="refresh",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="scrollbar",
        ),
        migrations.RemoveField(
            model_name="chatusers",
            name="skin",
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="allowskinoverride",
            field=models.IntegerField(db_column="allow_skin_override"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="autoloadrecent",
            field=models.IntegerField(db_column="autoload_recent"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="avatarlayout",
            field=models.CharField(db_column="avatar_layout", max_length=10),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="avatarpictures",
            field=models.IntegerField(db_column="avatar_pictures"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="avatartime",
            field=models.CharField(db_column="avatar_time", max_length=4),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="defaulthandle",
            field=models.CharField(
                blank=True, db_column="default_handle", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="defaultroom",
            field=models.CharField(
                blank=True, db_column="default_room", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="emailaddress",
            field=models.CharField(db_column="email_address", max_length=100),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="favoriteanime",
            field=models.TextField(db_column="favorite_anime"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="favoritemusic",
            field=models.TextField(db_column="favorite_music"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="favoritevideogames",
            field=models.TextField(db_column="favorite_video_games"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="firstcame",
            field=models.TextField(db_column="first_came"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="futureaspirations",
            field=models.TextField(db_column="future_aspirations"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="mosttimespent",
            field=models.TextField(db_column="most_time_spent"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="personalquote",
            field=models.TextField(db_column="personal_quote"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="preferredname",
            field=models.CharField(
                blank=True, db_column="preferred_name", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="randomphrase",
            field=models.TextField(db_column="random_phrase"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="realname",
            field=models.CharField(
                blank=True, db_column="real_name", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="scratchpadtext",
            field=models.TextField(db_column="scratchpad_text"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="scratchpadtime",
            field=models.DateTimeField(
                blank=True, db_column="scratchpad_time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="systemmessages",
            field=models.IntegerField(db_column="system_messages"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="timecreated",
            field=models.DateTimeField(db_column="time_created"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="timemodified",
            field=models.DateTimeField(db_column="time_modified"),
        ),
        migrations.AlterField(
            model_name="chatusers",
            name="timezoneoffset",
            field=models.DecimalField(
                db_column="timezone_offset", decimal_places=0, max_digits=2
            ),
        ),
        migrations.AlterField(
            model_name="handles",
            name="handlecolor",
            field=models.CharField(
                blank=True, db_column="handle_color", max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="handles",
            name="textcolor",
            field=models.CharField(
                blank=True, db_column="text_color", max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="handlename",
            field=models.CharField(db_column="handle_bame", max_length=50),
        ),
        migrations.AlterField(
            model_name="posts",
            name="roomname",
            field=models.CharField(db_column="room_name", max_length=30),
        ),
        migrations.AlterField(
            model_name="posts",
            name="tstamp",
            field=models.DateTimeField(db_column="datetime_posted"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="usertopm",
            field=models.CharField(db_column="user_to_PM", max_length=30),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="timecreated",
            field=models.DateTimeField(db_column="time_created"),
        ),
    ]
