# Generated by Django 4.0.2 on 2022-02-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_posts', '0023_change_django_model_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-datetime_posted']},
        ),
    ]
