# Generated by Django 4.0.2 on 2022-02-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_posts', '0024_alter_posts_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatUsers',
            new_name='ChatProfile',
        ),
    ]
