# Generated by Django 4.0.2 on 2022-02-24 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_posts', '0025_rename_chatusers_chatprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handles',
            old_name='chat_user',
            new_name='chat_profile',
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
