# Generated by Django 4.0.2 on 2022-02-24 06:00

from django.db import migrations


def create_users_from_legacy_data(apps, schema_editor):
    """
    Create
    """
    User = apps.get_model("auth", "User")
    ChatProfile = apps.get_model("chat_posts", "ChatProfile")
    for profile in ChatProfile.objects.all():
        user = User.objects.create_user(
            username=profile.name, password="1234", email=profile.email_address
        )
        profile.user = user
        user.save()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chat_posts", "0026_rename_chat_user_handles_chat_profile_and_more"),
    ]

    operations = [migrations.RunPython(create_users_from_legacy_data)]
