# Generated by Django 4.0.2 on 2022-02-24 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_posts', '0027_migrate_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatprofile',
            old_name='email_address',
            new_name='legacy_email_address',
        ),
        migrations.RenameField(
            model_name='chatprofile',
            old_name='name',
            new_name='legacy_name',
        ),
        migrations.RemoveField(
            model_name='chatprofile',
            name='password',
        ),
        migrations.AlterField(
            model_name='chatprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
